language: node_js
notifications:
  email: false
node_js:
    - '4'
    - '5'
    - '6'
addons:
  sauce_connect: true
env:
  global:
before_install:
- npm install
- ./node_modules/.bin/jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
before_script:
- npm start
script:
- npm run test:e2e