language: node_js
notifications:
    email: false
node_js:
    - '6'
addons:
    sauce_connect: true
before_script:
    - npm prune
    - npm run webdriver-update
    - npm run webdriver &
script:
    - npm start &
    - sleep 5
    - npm run test:e2e