language: node_js
notifications:
  email: false
node_js:
    - '4'
    - '5'
    - '6'
addons:
  sauce_connect: true
before_install:
- npm install http-server -g
before_script:
- npm run start
script:
- npm run test:e2e